config/routes.rb
Mehdix::Application.routes.draw do

  resources :licenses

  resources :shipments

  resources :vehicles

  resources :drivers
	
  resources :contracts

  resources :customers

  get "home/index"

   root :to => "home#index"

end

app/models/contract.rb
class Contract < ActiveRecord::Base
  	belongs_to :customer
	has_many :invoices, :dependent => :destroy
	has_many :shipments

	validates_presence_of :state	
#	validates_numericality_of :price
#	validates_presence_of :policy, :reason

	def self.search(search)
  		if search
  		  find(:all, :conditions => ['reason LIKE ?', "%#{search}%"])
 		 else
  		  find(:all)
  		end
	end
	

  include ActiveRecord::Transitions

	state_machine do
		state :pending		# initial
		state :reject		#
		state :agreed 		# go to invoiced state
		state :overdue		# may send email
		state :invoiced		# expext the payments
		state :completed	# done


	  event :reject do 
		transitions :to => :reject, :from => [:pending], :on_transition => :finishhh
	  end

	  event :agreed do
		transitions :to => :agreed, :from => [:pending]
	  end 

	  event :invoiced do
		transitions :to => :invoiced, :from => [:agreed], :on_transition => :mk_invoice
	  end

	  event :overdue do
		transitions :to => :overdue, :from => [:invoiced]
	  end

	  event :completed do
		transitions :to => :completed, :from => [:invoiced, :overdue]
	  end

	end 

	private 
	  def finishhh	
		@shipment.destroy
	  end
	
	private 
	  def mk_invoice	
		Invoice.new
	  end
end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
  # GET /contracts
  # GET /contracts.xml
  def index
    @contracts = Contract.all
	@shipment = Shipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @contracts }

	@contracts = Contract.search(params[:search]) # search parameter
    end
  end

  # GET /contracts/1
  # GET /contracts/1.xml
  def show
    @contract = Contract.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @contract }
    end
  end

  # GET /contracts/new
  # GET /contracts/new.xml
  def new
    @contract = Contract.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @contract }
    end
  end

  # GET /contracts/1/edit
  def edit
    @contract = Contract.find(params[:id])
  end

  # POST /contracts
  # POST /contracts.xml
  def create
    @contract = Contract.new(params[:contract])

    respond_to do |format|
      if @contract.save
        format.html { redirect_to(@contract, :notice => 'Contract was successfully created.') }
        format.xml  { render :xml => @contract, :status => :created, :location => @contract }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @contract.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /contracts/1
  # PUT /contracts/1.xml
  def update
    @contract = Contract.find(params[:id])

    respond_to do |format|
      if @contract.update_attributes(params[:contract])
        format.html { redirect_to(@contract, :notice => 'Contract was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @contract.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /contracts/1
  # DELETE /contracts/1.xml
  def destroy
    @contract = Contract.find(params[:id])
    @contract.destroy

    respond_to do |format|
      format.html { redirect_to(contracts_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/contracts_helper.rb
module ContractsHelper
end

app/views/contracts/_form.html.erb
<%= form_for(@contract) do |f| %>
  <% if @contract.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contract.errors.count, "error") %> prohibited this contract from being saved:</h2>

      <ul>
      <% @contract.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.datetime_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.datetime_select :end_at %>
  </div>
  <div class="field">
    <%= f.label :policy %><br />
    <%= f.text_field :policy %>
  </div>
  <div class="field">
    <%= f.label :reason %><br />
    <%= f.text_area :reason %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contracts/edit.html.erb
<h1>Editing contract</h1>

<%= render 'form' %>

<%= link_to 'Show', @contract %> |
<%= link_to 'Back', contracts_path %>

app/views/contracts/index.html.erb
<h1 class="head1">Listing contracts</h1>
<%= form_tag contracts_path, :method => 'get' do %>
  <p class="search_box">
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %> you can search in reason field
  </p>
<% end %>
<table>
  <tr>
    <th>State</th>
    <th>Price</th>
    <th>Start at</th>
    <th>End at</th>
    <th>Policy</th>
    <th>Reason</th>
    <th>Customer</th>
    <th></th>
    <th></th>
    <th></th>

  </tr>

<% @contracts.each do |contract| %>
  <tr>
    <td><%= contract.state %></td>
    <td><%= contract.price %></td>
    <td><%= contract.start_at %></td>
    <td><%= contract.end_at %></td>
    <td><%= contract.policy %></td>
    <td><%= contract.reason %></td>
    <td><%= contract.customer.id %></td>
    <td><%= link_to 'Show', contract %></td>
    <td><%= link_to 'Edit', edit_contract_path(contract) %></td>
    <td><%= link_to 'Destroy', contract, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Contract', new_contract_path %>

app/views/contracts/new.html.erb
<h1>New contract</h1>

<%= render 'form' %>

<%= link_to 'Back', contracts_path %>

app/views/contracts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
  <%= @contract.state %>
</p>

<p>
  <b>Price:</b>
  <%= @contract.price %>
</p>

<p>
  <b>Start at:</b>
  <%= @contract.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @contract.end_at %>
</p>

<p>
  <b>Policy:</b>
  <%= @contract.policy %>
</p>

<p>
  <b>Reason:</b>
  <%= @contract.reason %>
</p>

<p>
  <b>Customer:</b>
  <%= @contract.customer.id %>
</p>


<%= link_to 'Edit', edit_contract_path(@contract) %> |
<%= link_to 'Back', contracts_path %>