config/routes.rb
Mehdix::Application.routes.draw do

  resources :licenses

  resources :shipments

  resources :vehicles

  resources :drivers
	
  resources :contracts

  resources :customers

  get "home/index"

   root :to => "home#index"

end

app/models/driver.rb
class Driver < ActiveRecord::Base
	has_many :shipments
	has_many :licenses

	validates_presence_of :name, :address, :telephone

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  # GET /drivers
  # GET /drivers.xml
  def index
    @drivers = Driver.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @drivers }

	@licenses = License.all  # show license
    end
  end

  # GET /drivers/1
  # GET /drivers/1.xml
  def show
    @driver = Driver.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @driver }
    end
  end

  # GET /drivers/new
  # GET /drivers/new.xml
  def new
    @driver = Driver.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @driver }
    end
  end

  # GET /drivers/1/edit
  def edit
    @driver = Driver.find(params[:id])
  end

  # POST /drivers
  # POST /drivers.xml
  def create
    @driver = Driver.new(params[:driver])

    respond_to do |format|
      if @driver.save
        format.html { redirect_to(@driver, :notice => 'Driver was successfully created.') }
        format.xml  { render :xml => @driver, :status => :created, :location => @driver }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @driver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /drivers/1
  # PUT /drivers/1.xml
  def update
    @driver = Driver.find(params[:id])

    respond_to do |format|
      if @driver.update_attributes(params[:driver])
        format.html { redirect_to(@driver, :notice => 'Driver was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @driver.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /drivers/1
  # DELETE /drivers/1.xml
  def destroy
    @driver = Driver.find(params[:id])
    @driver.destroy

    respond_to do |format|
      format.html { redirect_to(drivers_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/_form.html.erb
<%= form_for(@driver) do |f| %>
  <% if @driver.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@driver.errors.count, "error") %> prohibited this driver from being saved:</h2>

      <ul>
      <% @driver.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br />
    <%= f.text_field :telephone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/drivers/edit.html.erb
<h1>Editing driver</h1>

<%= render 'form' %>

<%= link_to 'Show', @driver %> |
<%= link_to 'Back', drivers_path %>

app/views/drivers/index.html.erb
<h1>Listing drivers</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Telephone</th>
    <th>License type</th>
    <th></th>
<!--
    <th></th>
--->
  </tr>

<% @drivers.each do |driver| %>
  <tr>
    <td><%= driver.name %></td>
    <td><%= driver.address %></td>
    <td><%= driver.telephone %></td>
	<td><%=  License.find_by_driver_id(driver.id).type %></td>
    <td><%= link_to 'Show', driver %></td>
<!--
    <td><%= link_to 'Edit', edit_driver_path(driver) %></td>
    <td><%= link_to 'Destroy', driver, :confirm => 'Are you sure?', :method => :delete %></td>
-->
  </tr>
<% end %>
</table>

<br />

<!-- <%= link_to 'New Driver', new_driver_path %> -->

app/views/drivers/new.html.erb
<h1>New driver</h1>

<%= render 'form' %>

<%= link_to 'Back', drivers_path %>

app/views/drivers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @driver.name %>
</p>

<p>
  <b>Address:</b>
  <%= @driver.address %>
</p>

<p>
  <b>Telephone:</b>
  <%= @driver.telephone %>
</p>

<!--
<%= link_to 'Edit', edit_driver_path(@driver) %> |
-->
<%= link_to 'Back', drivers_path %>