config/routes.rb
Mehdix::Application.routes.draw do

  resources :licenses

  resources :shipments

  resources :vehicles

  resources :drivers
	
  resources :contracts

  resources :customers

  get "home/index"

   root :to => "home#index"

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
	has_many :shipments
	
	validates_presence_of :type
	validates_numericality_of :volume, :less_than => 10**6	
	validates_numericality_of :weight_capacity, :less_than => 10**2
end

class Car < Vehicle
end


class Lorry < Vehicle
end



class FlatBed < Vehicle 
end



class BoxVan < Vehicle 
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  # GET /vehicles
  # GET /vehicles.xml
  def index
    @vehicles = Vehicle.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @vehicles }
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.xml
  def show
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @vehicle }
    end
  end

  # GET /vehicles/new
  # GET /vehicles/new.xml
  def new
    @vehicle = Vehicle.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @vehicle }
    end
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  # POST /vehicles
  # POST /vehicles.xml
  def create
    @vehicle = Vehicle.new(params[:vehicle])

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to(@vehicle, :notice => 'Vehicle was successfully created.') }
        format.xml  { render :xml => @vehicle, :status => :created, :location => @vehicle }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @vehicle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /vehicles/1
  # PUT /vehicles/1.xml
  def update
    @vehicle = Vehicle.find(params[:id])

    respond_to do |format|
      if @vehicle.update_attributes(params[:vehicle])
        format.html { redirect_to(@vehicle, :notice => 'Vehicle was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @vehicle.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.xml
  def destroy
    @vehicle = Vehicle.find(params[:id])
    @vehicle.destroy

    respond_to do |format|
      format.html { redirect_to(vehicles_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/_form.html.erb
<%= form_for(@vehicle) do |f| %>
  <% if @vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% @vehicle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :type %><br />
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :weight_capacity %><br />
    <%= f.text_field :weight_capacity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing vehicle</h1>

<%= render 'form' %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1 class="head1">Listing vehicles</h1>

<table>
  <tr>
    <th>Type</th>
    <th>Volume</th>
    <th>Weight capacity</th>
    <th></th>
<!--
    <th></th>
    <th></th>
-->
  </tr>

<% @vehicles.each do |vehicle| %>
  <tr>
    <td><%= vehicle.type %></td>
    <td><%= vehicle.volume %></td>
    <td><%= vehicle.weight_capacity %></td>
    <td><%= link_to 'Show', vehicle_path(vehicle) %></td>
<!--
    <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
    <td><%= link_to 'Destroy', vehicle_path(vehicle), :confirm => 'Are you sure?', :method => :delete %></td>
-->
  </tr>
<% end %>
</table>

<br />
<!--
<%= link_to 'New Vehicle', new_vehicle_path %>
-->

app/views/vehicles/new.html.erb
<h1>New vehicle</h1>

<%= render 'form' %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Type:</b>
  <%= @vehicle.type %>
</p>

<p>
  <b>Volume:</b>
  <%= @vehicle.volume %>
</p>

<p>
  <b>Weight capacity:</b>
  <%= @vehicle.weight_capacity %>
</p>

<!--
<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
-->
<%= link_to 'Back', vehicles_path %>