config/routes.rb
Mehdix::Application.routes.draw do

  resources :licenses

  resources :shipments

  resources :vehicles

  resources :drivers
	
  resources :contracts

  resources :customers

  get "home/index"

   root :to => "home#index"

end

app/models/shipment.rb
class Shipment < ActiveRecord::Base
  	belongs_to :driver
  	belongs_to :vehicle
  	belongs_to :contract
	
	has_one :delivery
 	has_and_belongs_to_many :licenses

	
	
	validates_presence_of :state, :origin, :destination, :description
	validates_numericality_of :weight, :volume
	validates_presence_of :contract_id, :driver_id, :vehicle_id


  include ActiveRecord::Transitions

	state_machine do
		state :pending	# initial 
		state :delivered

	  event :delivered do
		transitions :to => :delivered, :from => [:pending]
	  end

	end	

end

app/controllers/shipments_controller.rb
class ShipmentsController < ApplicationController
  # GET /shipments
  # GET /shipments.xml
  def index
    @shipments = Shipment.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @shipments }
    end
  end

  # GET /shipments/1
  # GET /shipments/1.xml
  def show
    @shipment = Shipment.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/new
  # GET /shipments/new.xml
  def new
    @shipment = Shipment.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @shipment }
    end
  end

  # GET /shipments/1/edit
  def edit
    @shipment = Shipment.find(params[:id])
  end

  # POST /shipments
  # POST /shipments.xml
  def create
    @shipment = Shipment.new(params[:shipment])

    respond_to do |format|
      if @shipment.save
        format.html { redirect_to(@shipment, :notice => 'Shipment was successfully created.') }
        format.xml  { render :xml => @shipment, :status => :created, :location => @shipment }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /shipments/1
  # PUT /shipments/1.xml
  def update
    @shipment = Shipment.find(params[:id])

    respond_to do |format|
      if @shipment.update_attributes(params[:shipment])
        format.html { redirect_to(@shipment, :notice => 'Shipment was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @shipment.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /shipments/1
  # DELETE /shipments/1.xml
  def destroy
    @shipment = Shipment.find(params[:id])
    @shipment.destroy

    respond_to do |format|
      format.html { redirect_to(shipments_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/shipments_helper.rb
module ShipmentsHelper
end

app/views/shipments/_form.html.erb
<%= form_for(@shipment) do |f| %>
  <% if @shipment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shipment.errors.count, "error") %> prohibited this shipment from being saved:</h2>

      <ul>
      <% @shipment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :origin %><br />
    <%= f.text_area :origin %>
  </div>
  <div class="field">
    <%= f.label :destination %><br />
    <%= f.text_area :destination %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :weight %><br />
    <%= f.text_field :weight %>
  </div>
  <div class="field">
    <%= f.label :volume %><br />
    <%= f.text_field :volume %>
  </div>
  <div class="field">
    <%= f.label :slot_start_at %><br />
    <%= f.datetime_select :slot_start_at %>
  </div>
  <div class="field">
    <%= f.label :slot_end_at %><br />
    <%= f.datetime_select :slot_end_at %>
  </div>
  <div class="field">
    <%= f.label :driver %><br />
    <%= f.text_field :driver_id %>
  </div>
  <div class="field">
    <%= f.label :vehicle %><br />
    <%= f.text_field :vehicle_id %>
  </div>
  <div class="field">
    <%= f.label :contract %><br />
    <%= f.text_field :contract_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shipments/edit.html.erb
<h1>Editing shipment</h1>

<%= render 'form' %>

<%= link_to 'Show', @shipment %> |
<%= link_to 'Back', shipments_path %>

app/views/shipments/index.html.erb
<h1 class="head1">Listing shipments</h1>

<table>
  <tr>
    <th>State</th>
    <th>Origin</th>
    <th>Destination</th>
    <th>Description</th>
    <th>Weight</th>
    <th>Volume</th>
    <th>Slot start at</th>
    <th>Slot end at</th>
    <th>Driver</th>
    <th>Vehicle</th>
    <th>Contract</th>
    <th></th>
<!--
    <th></th>
    <th></th>
-->
  </tr>

<% @shipments.each do |shipment| %>
  <tr>
    <td><%= shipment.state %></td>
    <td><%= shipment.origin %></td>
    <td><%= shipment.destination %></td>
    <td><%= shipment.description %></td>
    <td><%= shipment.weight %></td>
    <td><%= shipment.volume %></td>
    <td><%= shipment.slot_start_at %></td>
    <td><%= shipment.slot_end_at %></td>
    <td><%= shipment.driver.name %></td>
    <td><%= shipment.vehicle.type %></td>
    <td><%= shipment.contract.id %></td>
    <td><%= link_to 'Show', shipment %></td>
<!--
    <td><%= link_to 'Edit', edit_shipment_path(shipment) %></td>
    <td><%= link_to 'Destroy', shipment, :confirm => 'Are you sure?', :method => :delete %></td>
-->
  </tr>
<% end %>
</table>

<br />
<!--
<%= link_to 'New Shipment', new_shipment_path %>
-->

app/views/shipments/new.html.erb
<h1>New shipment</h1>

<%= render 'form' %>

<%= link_to 'Back', shipments_path %>

app/views/shipments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>State:</b>
  <%= @shipment.state %>
</p>

<p>
  <b>Origin:</b>
  <%= @shipment.origin %>
</p>

<p>
  <b>Destination:</b>
  <%= @shipment.destination %>
</p>

<p>
  <b>Description:</b>
  <%= @shipment.description %>
</p>

<p>
  <b>Weight:</b>
  <%= @shipment.weight %>
</p>

<p>
  <b>Volume:</b>
  <%= @shipment.volume %>
</p>

<p>
  <b>Slot start at:</b>
  <%= @shipment.slot_start_at %>
</p>

<p>
  <b>Slot end at:</b>
  <%= @shipment.slot_end_at %>
</p>

<p>
  <b>Driver:</b>
  <%= @shipment.driver.name %>
</p>

<p>
  <b>Vehicle:</b>
  <%= @shipment.vehicle.type %>
</p>

<p>
  <b>Contract:</b>
  <%= @shipment.contract.id %>
</p>

<!--
<%= link_to 'Edit', edit_shipment_path(@shipment) %> |
-->
<%= link_to 'Back', shipments_path %>